# Generated by Django 3.2 on 2022-10-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=20)),
                ('friendly_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['level_name'],
            },
        ),
        migrations.AlterField(
            model_name='workshop',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='workshops.level'),
        ),
    ]
