# Generated by Django 3.2 on 2022-11-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshoptestimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['date']},
        ),
    ]
