# Generated by Django 3.2 on 2022-11-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('request_type', models.CharField(choices=[('QUOTE', 'Get a quote for a custom order'), ('QUESTION', 'Ask a question')], default='QUESTION', max_length=30)),
                ('reference_link', models.URLField(blank=True)),
                ('request_body', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
