# Generated by Django 3.2 on 2022-11-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequest',
            name='request_type',
            field=models.CharField(choices=[('QUOTE', 'Get a quote for a custom order'), ('QUESTION', 'Ask a question'), ('RESERVATION', 'Save your spot')], default='QUESTION', max_length=30),
        ),
    ]
